export type FreeRunner = {
  id: string;
  name: string;
  kind: "android" | "public" | "gpu";
  description: string;
  capabilities: string[];
  url: string;
  notes: string;
  priority: number;
};

/** Free/no-key routes. Runtime validates live API and actual media artifacts. */
export const FREE_RUNNERS: FreeRunner[] = [
  {
    id: "cf-qwen3-chat",
    name: "Cloudflare Qwen3",
    kind: "public",
    description: "Server-side Buddy conversation engine.",
    capabilities: ["chat", "conversation", "text-generation", "text"],
    url: "/api/ai/chat",
    notes: "Server route.",
    priority: 300,
  },
  {
    id: "cf-gpt-oss-chat",
    name: "Cloudflare GPT-OSS",
    kind: "public",
    description: "Open-weight conversational fallback.",
    capabilities: ["chat", "conversation", "text-generation", "text"],
    url: "/api/ai/chat",
    notes: "Server fallback.",
    priority: 295,
  },
  {
    id: "cf-buddy-tts",
    name: "Buddy Voice Engine",
    kind: "public",
    description: "Fast server-side multilingual speech for everyday Buddy voices.",
    capabilities: ["tts"],
    url: "/api/ai/tts",
    notes: "Preset speech only; clone engines are excluded from this pool.",
    priority: 500,
  },
  {
    id: "hf-chatterbox-v3",
    name: "EchoForge 23",
    kind: "public",
    description: "Natural multilingual reference-voice cloning with strong speaker similarity.",
    capabilities: ["voice-clone"],
    url: "https://huggingface.co/spaces/ResembleAI/Chatterbox-Multilingual-TTS-V3",
    notes: "Primary clone route. Authorized reference audio only.",
    priority: 650,
  },
  {
    id: "hf-chatterbox",
    name: "EchoForge",
    kind: "public",
    description: "Expressive English reference-voice cloning fallback.",
    capabilities: ["voice-clone"],
    url: "https://huggingface.co/spaces/ResembleAI/Chatterbox",
    notes: "Secondary clone route. Authorized reference audio only.",
    priority: 600,
  },
  {
    id: "hf-cosyvoice3",
    name: "Velvet",
    kind: "public",
    description: "Multilingual zero-shot cloning with expressive delivery controls.",
    capabilities: ["voice-clone", "voice-swap"],
    url: "https://huggingface.co/spaces/FunAudioLLM/Fun-CosyVoice3-0.5B",
    notes: "Secondary multilingual clone route.",
    priority: 560,
  },
  {
    id: "hf-seed-vc",
    name: "Shift",
    kind: "public",
    description: "Voice-conversion fallback for authorized source voices.",
    capabilities: ["voice-swap", "voice-clone"],
    url: "https://huggingface.co/spaces/Plachta/Seed-VC",
    notes: "Authorized voices only.",
    priority: 350,
  },
  {
    id: "hf-applio",
    name: "Forge",
    kind: "public",
    description: "Open voice-conversion fallback for authorized voices.",
    capabilities: ["voice", "voice-swap", "singing-voice-conversion", "voice-clone"],
    url: "https://huggingface.co/spaces/IAHispano/ApplioX",
    notes: "Authorized voices only.",
    priority: 300,
  },
  {
    id: "hf-moss-tts",
    name: "MOSS-TTS",
    kind: "public",
    description: "Multilingual cloning fallback.",
    capabilities: ["voice-clone"],
    url: "https://huggingface.co/spaces/fnlp/MOSS-TTS",
    notes: "Clone-only route; never selected for preset voices.",
    priority: 280,
  },
  {
    id: "hf-qwen3-tts",
    name: "Qwen3-TTS Custom Voices",
    kind: "public",
    description: "Preset speaker and clone fallback with explicit speaker routing.",
    capabilities: ["tts", "voice-clone"],
    url: "https://huggingface.co/spaces/Qwen/Qwen3-TTS",
    notes: "Last resort only; public ZeroGPU capacity may be exhausted.",
    priority: 120,
  },
  {
    id: "hf-qwen3-chat",
    name: "Qwen3",
    kind: "public",
    description: "Free conversational fallback.",
    capabilities: ["chat", "conversation", "text-generation"],
    url: "https://huggingface.co/spaces/Qwen/Qwen3-Demo",
    notes: "Live validation required.",
    priority: 180,
  },
  {
    id: "hf-qwen3-omni-chat",
    name: "Qwen3 Omni",
    kind: "public",
    description: "Multimodal conversational fallback.",
    capabilities: ["chat", "conversation", "text-generation"],
    url: "https://huggingface.co/spaces/Qwen/Qwen3-Omni-Demo",
    notes: "Live validation required.",
    priority: 170,
  },
  {
    id: "cf-flux-2-klein",
    name: "Cloudflare FLUX.2 Klein 4B",
    kind: "gpu",
    description: "Server-side text-to-image generation and editing.",
    capabilities: ["image", "image-generation", "artwork", "cover"],
    url: "/api/ai/image",
    notes: "Server route.",
    priority: 300,
  },
  {
    id: "cf-seedance-fast",
    name: "Cloudflare Seedance 2.0 Fast",
    kind: "gpu",
    description: "Text-to-video and image-to-video generation.",
    capabilities: ["video", "video-generation", "image-to-video", "animation"],
    url: "/api/ai/video",
    notes: "Server route.",
    priority: 300,
  },
  {
    id: "cf-music-26",
    name: "Cloudflare MiniMax Music 2.6",
    kind: "gpu",
    description: "Song and instrumental music generation.",
    capabilities: ["music", "song", "lyrics-to-music", "audio-generation"],
    url: "/api/ai/music",
    notes: "Server route.",
    priority: 300,
  },
  {
    id: "hf-demucs",
    name: "Demucs Stem Separation",
    kind: "gpu",
    description: "Real vocal/drum/bass/other separation.",
    capabilities: ["vocal-separation", "stems", "audio-separation"],
    url: "https://huggingface.co/spaces/owiedotch/demucs-stem-separation",
    notes: "Actual separated audio required.",
    priority: 170,
  },
];

export function runnersFor(capability: string): FreeRunner[] {
  return FREE_RUNNERS.filter((r) => r.capabilities.includes(capability)).sort(
    (a, b) => b.priority - a.priority,
  );
}
