export type FreeRunner = {
  id: string;
  name: string;
  kind: "android" | "public" | "gpu";
  description: string;
  capabilities: string[];
  url: string;
  notes: string;
  priority: number;
};

/** Free/no-key routes. Every route is a candidate; runtime validates its live API and artifact. */
export const FREE_RUNNERS: FreeRunner[] = [
  {
    id: "cf-qwen3-chat",
    name: "Cloudflare Qwen3",
    kind: "public",
    description: "Server-side Buddy text generation without exposing an API key.",
    capabilities: ["chat", "conversation", "text-generation", "text"],
    url: "/api/ai/chat",
    notes: "Uses the repository's Cloudflare Workers AI binding.",
    priority: 300,
  },
  {
    id: "cf-gpt-oss-chat",
    name: "Cloudflare GPT-OSS",
    kind: "public",
    description: "Current open-weight conversational fallback.",
    capabilities: ["chat", "conversation", "text-generation", "text"],
    url: "/api/ai/chat",
    notes: "Server-side fallback; no client key.",
    priority: 295,
  },
  {
    id: "hf-qwen3-chat",
    name: "Qwen3",
    kind: "public",
    description: "Free conversational fallback for Buddy.",
    capabilities: ["chat", "conversation", "text-generation", "text"],
    url: "https://huggingface.co/spaces/Qwen/Qwen3-Demo",
    notes: "Live Gradio API discovery and artifact validation required.",
    priority: 180,
  },
  {
    id: "hf-qwen3-omni-chat",
    name: "Qwen3 Omni",
    kind: "public",
    description: "Multimodal conversational fallback.",
    capabilities: ["chat", "conversation", "text-generation"],
    url: "https://huggingface.co/spaces/Qwen/Qwen3-Omni-Demo",
    notes: "Live API compatibility required.",
    priority: 170,
  },
  {
    id: "hf-deepseek-janus-pro",
    name: "DeepSeek Janus-Pro",
    kind: "public",
    description: "DeepSeek multimodal fallback for visual understanding and creative tasks.",
    capabilities: ["chat", "conversation", "text-generation", "image", "vision"],
    url: "https://huggingface.co/spaces/deepseek-ai/Janus-Pro-7B",
    notes: "Official DeepSeek Space; live Gradio API and artifact validation required.",
    priority: 185,
  },
  {
    id: "hf-kimi-vl-a3b",
    name: "Kimi VL A3B Thinking",
    kind: "public",
    description: "Compact multimodal Kimi fallback for images, video and documents.",
    capabilities: ["chat", "conversation", "text-generation", "vision", "image", "video"],
    url: "https://huggingface.co/spaces/moonshotai/Kimi-VL-A3B-Thinking-2506",
    notes: "Official Moonshot Space; live API compatibility required.",
    priority: 180,
  },
  {
    id: "hf-mistral-devstral-api",
    name: "Mistral Devstral",
    kind: "public",
    description: "Strong coding/agentic fallback when available through a public Space.",
    capabilities: ["chat", "conversation", "text-generation", "coding", "reasoning"],
    url: "https://huggingface.co/spaces/aiqcamp/Mistral-Devstral-API",
    notes: "Public Space route; live API validation required and may be unavailable at times.",
    priority: 175,
  },
  {
    id: "hf-gemma4-webgpu",
    name: "Gemma 4 WebGPU",
    kind: "android",
    description: "Browser-local Google Gemma fallback on capable Android devices.",
    capabilities: ["chat", "conversation", "text-generation", "writing", "reasoning"],
    url: "https://huggingface.co/spaces/webml-community/gemma-4-webgpu",
    notes: "Runs locally in the browser when the device supports the required WebGPU path.",
    priority: 165,
  },
  {
    id: "cf-flux-2-klein",
    name: "Cloudflare FLUX.2 Klein 4B",
    kind: "gpu",
    description: "Real server-side text-to-image generation and editing.",
    capabilities: ["image", "image-generation", "artwork", "cover"],
    url: "/api/ai/image",
    notes: "Uses the current FLUX.2 Klein 4B multipart binding.",
    priority: 300,
  },
  {
    id: "cf-seedance-fast",
    name: "Cloudflare Seedance 2.0 Fast",
    kind: "gpu",
    description: "Real text-to-video and image-to-video generation with optional audio.",
    capabilities: ["video", "video-generation", "image-to-video", "animation"],
    url: "/api/ai/video",
    notes: "Uses the current unified Cloudflare AI catalog route.",
    priority: 300,
  },
  {
    id: "cf-music-26",
    name: "Cloudflare MiniMax Music 2.6",
    kind: "gpu",
    description: "Real full-song and instrumental music generation.",
    capabilities: ["music", "song", "lyrics-to-music", "audio-generation"],
    url: "/api/ai/music",
    notes: "Uses the current unified Cloudflare AI music route; returns a real audio URL.",
    priority: 300,
  },
  {
    id: "hf-qwen3-webgpu",
    name: "Qwen3 WebGPU",
    kind: "android",
    description: "Browser-local writing fallback.",
    capabilities: ["text", "writing", "lyrics"],
    url: "https://huggingface.co/spaces/webml-community/qwen3-webgpu",
    notes: "Optional device-local route.",
    priority: 125,
  },
  {
    id: "hf-ace-step-15",
    name: "ACE-Step 1.5",
    kind: "public",
    description: "Full-song music generation fallback.",
    capabilities: ["music", "song", "lyrics-to-music", "audio-to-audio"],
    url: "https://huggingface.co/spaces/ACE-Step/Ace-Step-v1.5",
    notes: "Fallback only; live schema and real artifact required.",
    priority: 160,
  },
  {
    id: "hf-diffrhythm2",
    name: "DiffRhythm 2",
    kind: "public",
    description: "Lyrics-conditioned song generation fallback.",
    capabilities: ["music", "song", "lyrics-to-music", "style-conditioning"],
    url: "https://huggingface.co/spaces/ASLP-lab/DiffRhythm2",
    notes: "Fallback only; live schema and real audio artifact required.",
    priority: 150,
  },
  {
    id: "hf-qwen3-tts-customvoice",
    name: "Qwen3-TTS Custom Voice",
    kind: "public",
    description: "Primary natural preset-voice TTS route with real selectable speakers.",
    capabilities: ["voice", "tts", "multilingual-tts", "voice-design", "voice-preview"],
    url: "https://huggingface.co/spaces/Qwen/Qwen3-TTS",
    notes: "Qwen official Space; runtime must validate live Gradio API and audio artifact.",
    priority: 330,
  },
  {
    id: "hf-qwen3-tts-clone",
    name: "Qwen3-TTS Voice Clone",
    kind: "public",
    description: "Primary authorized voice-cloning route using a user reference sample.",
    capabilities: ["voice", "tts", "voice-clone", "multilingual-tts"],
    url: "https://huggingface.co/spaces/Qwen/Qwen3-TTS",
    notes: "Uses Qwen3-TTS Base voice cloning; requires user-owned/authorized reference audio and live artifact validation.",
    priority: 325,
  },
  {
    id: "hf-faster-qwen3-tts",
    name: "Faster Qwen3-TTS",
    kind: "public",
    description: "Low-latency Qwen3-TTS fallback for conversational speech.",
    capabilities: ["voice", "tts", "voice-clone", "streaming-tts"],
    url: "https://huggingface.co/spaces/HuggingFaceM4/faster-qwen3-tts-demo",
    notes: "Live Space; validate schema and playable audio before accepting result.",
    priority: 315,
  },
  {
    id: "cf-melotts",
    name: "Cloudflare MeloTTS",
    kind: "gpu",
    description: "Server-side Buddy speech generation fallback.",
    capabilities: ["voice", "tts", "multilingual-tts"],
    url: "/api/ai/tts",
    notes: "Fallback route; do not use as the selectable-speaker implementation.",
    priority: 300,
  },
  {
    id: "cf-aura-2",
    name: "Cloudflare Aura-2",
    kind: "gpu",
    description: "Natural TTS fallback when higher-priority voice routes are unavailable.",
    capabilities: ["voice", "tts"],
    url: "/api/ai/tts",
    notes: "Server-side fallback.",
    priority: 295,
  },
  {
    id: "cf-whisper",
    name: "Cloudflare Whisper",
    kind: "gpu",
    description: "Reliable server-side speech recognition for Android voice chat.",
    capabilities: ["speech-to-text", "transcription", "realtime-asr"],
    url: "/api/ai/speech-to-text",
    notes: "Audio is sent to the server and transcribed with current Whisper.",
    priority: 300,
  },
  {
    id: "hf-openai-whisper",
    name: "Hugging Face OpenAI Whisper",
    kind: "public",
    description: "Independent Whisper speech-recognition fallback when Cloudflare ASR is unavailable.",
    capabilities: ["speech-to-text", "transcription", "asr"],
    url: "https://huggingface.co/spaces/openai/whisper",
    notes: "Uses the public Gradio Whisper Space; subject to Space availability/rate limits.",
    priority: 180,
  },
  {
    id: "hf-moss-tts-15",
    name: "MOSS-TTS v1.5",
    kind: "public",
    description: "Open multilingual TTS and voice cloning fallback.",
    capabilities: ["voice", "voice-clone", "tts", "multilingual-tts"],
    url: "https://huggingface.co/spaces/OpenMOSS-Team/MOSS-TTS-v1.5",
    notes: "Fallback only; live schema and audio artifact required.",
    priority: 180,
  },
  {
    id: "hf-chatterbox-turbo",
    name: "Chatterbox Turbo",
    kind: "public",
    description: "Natural open-source TTS fallback.",
    capabilities: ["voice", "tts", "voice-clone"],
    url: "https://huggingface.co/spaces/ResembleAI/chatterbox-turbo-demo",
    notes: "Fallback only; live schema and audio artifact required.",
    priority: 170,
  },
  {
    id: "hf-chatterbox-multilingual",
    name: "Chatterbox Multilingual",
    kind: "public",
    description: "Multilingual TTS and voice-cloning fallback.",
    capabilities: ["voice", "voice-clone", "tts", "multilingual-tts"],
    url: "https://huggingface.co/spaces/ResembleAI/Chatterbox-Multilingual-TTS",
    notes: "Fallback only; live schema and audio artifact required.",
    priority: 160,
  },
  {
    id: "hf-seed-vc",
    name: "Seed-VC",
    kind: "public",
    description: "Zero-shot speech and singing voice conversion.",
    capabilities: ["voice", "voice-swap", "singing-voice-conversion"],
    url: "https://huggingface.co/spaces/Plachta/Seed-VC",
    notes: "Use only voices the user owns or is authorized to transform.",
    priority: 160,
  },
  {
    id: "hf-applio",
    name: "Applio / RVC",
    kind: "public",
    description: "Open RVC voice conversion.",
    capabilities: ["voice", "voice-swap", "singing-voice-conversion", "voice-training"],
    url: "https://huggingface.co/spaces/IAHispano/ApplioX",
    notes: "Live API compatibility required.",
    priority: 135,
  },
  {
    id: "hf-ltx-video",
    name: "LTX Video Fast",
    kind: "gpu",
    description: "Video generation fallback.",
    capabilities: ["video", "video-generation", "image-to-video"],
    url: "https://huggingface.co/spaces/Lightricks/ltx-video-distilled",
    notes: "Fallback only; live schema and actual video artifact required.",
    priority: 200,
  },
  {
    id: "hf-wan22-fast",
    name: "Wan2.2 14B Fast",
    kind: "gpu",
    description: "Image-to-video fallback.",
    capabilities: ["video", "video-generation", "image-to-video", "animation"],
    url: "https://huggingface.co/spaces/zerogpu-aoti/wan2-2-fp8da-aoti-faster",
    notes: "Fallback only; requires compatible image input.",
    priority: 190,
  },
  {
    id: "hf-demucs",
    name: "Demucs Stem Separation",
    kind: "gpu",
    description: "Real vocal/drum/bass/other stem separation.",
    capabilities: ["vocal-separation", "stems", "audio-separation"],
    url: "https://huggingface.co/spaces/owiedotch/demucs-stem-separation",
    notes: "Live Space; output must contain actual separated audio artifacts.",
    priority: 170,
  },
];

export function runnersFor(capability: string): FreeRunner[] {
  return FREE_RUNNERS.filter((runner) => runner.capabilities.includes(capability)).sort(
    (a, b) => b.priority - a.priority,
  );
}
