const BACKEND = "free-chatterbox-cpu-first";
const VERSION = "voice-clone-v9.1";
const HF_CPU_SPACE = "https://rahul7star-chatterbox-multilingual-tts-api.hf.space";
const HF_GPU_SPACE = "https://resembleai-chatterbox.hf.space";
const DEFAULT_TEXT = "Hello. This is your cloned voice sample. Would you like to use this voice for Buddy now, or would you like to record again?";
type CloneEnv={HF_TOKEN?:string;CHATTERBOX_ENDPOINT?:string;CHATTERBOX_TOKEN?:string};
type CloneBody={audioBase64?:string;audio?:string;refAudio?:string;referenceAudio?:string;audioMimeType?:string;text?:string;target_text?:string;prompt?:string};
function headers(){const h=new Headers({"cache-control":"no-store, no-cache, must-revalidate"});h.set("x-buddy-clone-backend",BACKEND);h.set("x-buddy-clone-version",VERSION);return h;}
function errorJson(message:string,status:number){return Response.json({ok:false,backend:BACKEND,version:VERSION,error:message},{status,headers:headers()});}
function normalizeMime(raw:string,name=""){const mime=String(raw||"").toLowerCase().split(";")[0].trim();if(mime.startsWith("audio/"))return mime;const ext=name.toLowerCase().split(".").pop()||"";return({wav:"audio/wav",wave:"audio/wav",mp3:"audio/mpeg",m4a:"audio/mp4",mp4:"audio/mp4",aac:"audio/aac",ogg:"audio/ogg",oga:"audio/ogg",opus:"audio/opus",webm:"audio/webm",flac:"audio/flac"}as Record<string,string>)[ext]||"application/octet-stream";}
function decodeBase64(value:string,mime="audio/wav"){const m=value.match(/^data:([^;,]+)(?:;[^,]*)?;base64,(.*)$/s);const raw=(m?.[2]||value).replace(/\s/g,"");let binary="";try{binary=atob(raw);}catch{throw new Error("The uploaded voice sample is not valid base64 audio.");}const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return{bytes,mime:normalizeMime(m?.[1]||mime)};}
async function readInput(request:Request){if((request.headers.get("content-type")||"").toLowerCase().includes("multipart/form-data")){const form=await request.formData();const file=["audio","file","voice","referenceAudio","refAudio"].map(k=>form.get(k)).find(v=>v instanceof File) as File|undefined;if(!file?.size)throw new Error("No usable voice sample was uploaded.");return{bytes:new Uint8Array(await file.arrayBuffer()),mime:normalizeMime(file.type,file.name),name:file.name||"voice-reference.wav",text:String(form.get("text")||form.get("target_text")||form.get("prompt")||"").trim()};}let body:CloneBody;try{body=await request.json();}catch{throw new Error("The clone request was not valid JSON or multipart form data.");}const encoded=body.audioBase64||body.audio||body.refAudio||body.referenceAudio;if(!encoded)throw new Error("A voice sample is required.");const d=decodeBase64(encoded,body.audioMimeType||"audio/wav");return{bytes:d.bytes,mime:d.mime,name:"voice-reference.wav",text:(body.text||body.target_text||body.prompt||"").trim()};}
function audioResponse(bytes:Uint8Array,contentType:string,provider:string){if(bytes.length<4096)throw new Error("The voice service returned an empty or unusably small audio file.");const wav=bytes.length>=12&&new TextDecoder().decode(bytes.subarray(0,4))==="RIFF"&&new TextDecoder().decode(bytes.subarray(8,12))==="WAVE";if(!contentType.toLowerCase().startsWith("audio/")&&!wav)throw new Error("The voice service returned non-audio data; clone was not verified.");const h=headers();h.set("content-type",contentType.toLowerCase().startsWith("audio/")?contentType:"audio/wav");h.set("content-length",String(bytes.length));h.set("x-clone-provider",provider);h.set("x-clone-verified","true");return new Response(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer,{status:200,headers:h});}
async function uploadReference(base:string,input:{bytes:Uint8Array;mime:string;name:string}){const form=new FormData();const ab=input.bytes.buffer.slice(input.bytes.byteOffset,input.bytes.byteOffset+input.bytes.byteLength) as ArrayBuffer;form.append("files",new Blob([ab],{type:input.mime}),input.name);const r=await fetch(`${base}/gradio_api/upload`,{method:"POST",body:form});if(!r.ok)throw new Error(`Chatterbox CPU upload failed (${r.status}).`);const j=await r.json() as unknown;const path=Array.isArray(j)?String(j[0]||""):"";if(!path)throw new Error("Chatterbox CPU backend did not return a reference-file path.");return path;}
async function callCpuSpace(input:{bytes:Uint8Array;mime:string;name:string},text:string){const path=await uploadReference(HF_CPU_SPACE,input);const data=[text.slice(0,300),"","Speak 🗣️","en",{path,meta:{_type:"gradio.FileData"},orig_name:input.name,mime_type:input.mime},0.5,0.8,0,0.5];const q=await fetch(`${HF_CPU_SPACE}/gradio_api/call/generate_tts_audio`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({data})});if(!q.ok)throw new Error(`Chatterbox CPU queue failed (${q.status}).`);const {event_id}=await q.json() as {event_id?:string};if(!event_id)throw new Error("Chatterbox CPU backend returned no event ID.");const result=await fetch(`${HF_CPU_SPACE}/gradio_api/call/generate_tts_audio/${encodeURIComponent(event_id)}`,{headers:{Accept:"text/event-stream"}});if(!result.ok)throw new Error(`Chatterbox CPU generation failed (${result.status}).`);const stream=await result.text();let complete="",failure="";for(const block of stream.split(/\n\s*\n/)){const ev=block.match(/^event:\s*(.+)$/m)?.[1]?.trim();const d=block.match(/^data:\s*(.*)$/m)?.[1]?.trim()||"";if(ev==="complete")complete=d;if(ev==="error")failure=d;}if(failure)throw new Error(`Chatterbox CPU generation error: ${failure}`);if(!complete)throw new Error("Chatterbox CPU backend returned no completed audio.");let output:unknown;try{output=JSON.parse(complete);}catch{throw new Error("Chatterbox CPU returned malformed completion data.");}const first=Array.isArray(output)?output[0]:null;const url=typeof first==="string"?first:first&&typeof first==="object"?String((first as Record<string,unknown>).url||(first as Record<string,unknown>).path||""):"";if(!url)throw new Error("Chatterbox CPU completed without an audio artifact.");const audio=await fetch(url.startsWith("http")?url:`${HF_CPU_SPACE}/gradio_api/file=${url}`);if(!audio.ok)throw new Error(`Chatterbox CPU audio fetch failed (${audio.status}).`);return audioResponse(new Uint8Array(await audio.arrayBuffer()),audio.headers.get("content-type")||"audio/wav","Chatterbox Multilingual CPU — Hugging Face Space");}
async function cloneViaSelfHosted(input:{bytes:Uint8Array;mime:string;name:string},text:string,env:CloneEnv){if(!env.CHATTERBOX_ENDPOINT?.trim())return null;const form=new FormData();const ab=input.bytes.buffer.slice(input.bytes.byteOffset,input.bytes.byteOffset+input.bytes.byteLength) as ArrayBuffer;form.append("audio",new Blob([ab],{type:input.mime}),input.name);form.append("text",text);const h:Record<string,string>={};if(env.CHATTERBOX_TOKEN)h.Authorization=`Bearer ${env.CHATTERBOX_TOKEN}`;const r=await fetch(env.CHATTERBOX_ENDPOINT,{method:"POST",headers:h,body:form});const b=new Uint8Array(await r.arrayBuffer());if(!r.ok)throw new Error(`Self-hosted Chatterbox failed (${r.status}).`);return audioResponse(b,r.headers.get("content-type")||"audio/wav","self-hosted Chatterbox");}
export function voiceCloneHealth(env?:CloneEnv){return Response.json({ok:true,capability:"voice-clone",backend:BACKEND,version:VERSION,transcriptRequired:false,primary:env?.CHATTERBOX_ENDPOINT?"self-hosted-chatterbox":"free-chatterbox-cpu-space",fallback:"official Chatterbox Hugging Face Space"},{headers:headers()});}
export async function handleProductionVoiceClone(request:Request,env:CloneEnv){if(request.method!=="POST")return errorJson("POST required.",405);try{const input=await readInput(request);if(input.bytes.length<4096)throw new Error("The voice sample is too short or empty.");const text=input.text||DEFAULT_TEXT;if(env.CHATTERBOX_ENDPOINT){try{const r=await cloneViaSelfHosted(input,text,env);if(r)return r;}catch(e){console.warn(`[voice-clone] self-hosted failed: ${e instanceof Error?e.message:String(e)}`);}}try{return await callCpuSpace(input,text);}catch(e){console.warn(`[voice-clone] free CPU Space failed: ${e instanceof Error?e.message:String(e)}`);}if(env.HF_TOKEN){throw new Error("Free CPU Chatterbox backend failed; hosted inference fallback intentionally not used until capacity is available.");}throw new Error("No free Chatterbox backend returned a verified playable audio artifact.");}catch(e){return errorJson(e instanceof Error?e.message:"Voice cloning failed.",502);}}
