import { Client, handle_file } from "@gradio/client";
import { FREE_RUNNERS, type FreeRunner, runnersFor } from "./free-runners";
import { getBuddyVoiceProfile, getBuddyVoiceSample } from "./buddy-voice";
export type StudioCapability = "chat" | "speech-to-text" | "music" | "image" | "video" | "voice-clone" | "voice-swap" | "vocal-separation" | "tts";
export type StudioJobInput = Record<string, unknown>;
export type StudioArtifact = { capability: StudioCapability; value: unknown; url: string | null; provider: string };
type Parameter={parameter_name?:string;label?:string;component?:string;type?:string;default?:unknown;optional?:boolean;parameter_has_default?:boolean};
type Endpoint={parameters?:Parameter[];description?:string;fn?:string}; type Api={named_endpoints?:Record<string,Endpoint>;unnamed_endpoints?:Record<string,Endpoint>};
const clients=new Map<string,Promise<Client>>(),apis=new Map<string,{api:Api;expires:number}>();
const norm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]/g,"");
const aliases:Record<string,string[]>={prompt:["prompt","text","message","query","question","lyrics","targettext","ttstext","targettextinput"],text:["text","prompt","message","lyrics","targettext","ttstext","inputtext"],targettext:["targettext","text","prompt","message","ttstext"],reftext:["reftext","referencetext","transcript","referencetranscript","clonereftext"],referencetext:["referencetext","reftext","transcript","referencetranscript","clonereftext"],audio:["audio","inputaudio","sourceaudio","referenceaudio","refaudio","file","refaudioupload","clonerefaudio"],refaudio:["refaudio","referenceaudio","audio","file","refaudioupload","clonerefaudio"],referenceaudio:["referenceaudio","refaudio","audio","file"],speaker:["speaker","voice","speakerid","voiceid","ttsspeaker","voicespeaker"],modelsize:["modelsize","model","size","ttsmodelsize","clonemodelsize"],usexvectoronly:["usexvectoronly","xvectoronly","xvector","clonexvector"],language:["language","lang","ttslanguage","clonelanguage"]};
function pick(name:string,input:StudioJobInput){const n=norm(name);for(const[k,v]of Object.entries(input))if(norm(k)===n&&v!=null)return v;for(const a of aliases[n]??[])for(const[k,v]of Object.entries(input))if(norm(k)===norm(a)&&v!=null)return v;if(n.includes("targettext")||n.includes("ttstext")||n.includes("inputtext"))return input.target_text??input.text??input.prompt;if(n.includes("reftext")||n.includes("referencetext")||n.includes("transcript"))return input.referenceTranscript??input.refText??input.transcript;if(n.includes("speaker")||n.includes("voiceid"))return input.speaker;if(n.includes("modelsize")||n==="model"||n.includes("ttsmodel"))return input.model_size??input.modelSize;if(n.includes("xvector"))return input.use_xvector_only??input.useXvectorOnly;if(n.includes("language")||n.includes("lang"))return input.language;if(n.includes("refaudio")||n.includes("referenceaudio")||n.includes("clonerefaudio"))return input.refAudio??input.referenceAudio??input.audio;if(n.includes("audio"))return input.audio??input.refAudio??input.referenceAudio;if(n.includes("history")||n.includes("conversation"))return input.history??input.messages??[];return undefined;}
function canonicalSpeaker(value:unknown){if(typeof value!=="string")return value;const n=norm(value);const map:Record<string,string>={ryan:"Ryan",aiden:"Aiden",vivian:"Vivian",serena:"Serena",dylan:"Dylan",eric:"Eric",onoanna:"Ono_anna",sohee:"Sohee",unclefu:"Uncle_fu"};return map[n]??value;}
function fallback(p:Parameter){if(p.default!=null)return p.default;if(p.optional||p.parameter_has_default)return undefined;const n=norm(p.parameter_name??p.label??"");if(n.includes("seed"))return -1;if(n.includes("steps"))return 16;if(n.includes("modelsize")||n==="model")return "0.6B";if(n.includes("xvector"))return true;if(n.includes("language")||n.includes("lang"))return "English";return undefined;}
function endpoints(api:Api){return{...(api.named_endpoints??{}),...(api.unnamed_endpoints??{})};}
function spaceId(space:string){return space.replace(/^https?:\/\/huggingface\.co\/spaces\//,"").replace(/\/$/,"");}
function proxyOrigin(space:string){return `${window.location.origin}/api/hf-space/${encodeURIComponent(spaceId(space))}`;}
function artifactUrl(v:unknown):string|null{if(typeof v==="string")return/^(https?:|blob:|data:|\/)/i.test(v)?v:null;if(typeof Blob!=="undefined"&&v instanceof Blob)return URL.createObjectURL(v);if(Array.isArray(v))for(const x of v){const u=artifactUrl(x);if(u)return u;}if(v&&typeof v==="object")for(const k of["url","uri","src","path","value","data","audio","file"]){const u=artifactUrl((v as Record<string,unknown>)[k]);if(u)return u;}return null;}
function output(v:unknown):boolean{if(v==null)return false;if(typeof v==="string")return v.trim().length>0;if(typeof Blob!=="undefined"&&v instanceof Blob)return v.size>0;if(Array.isArray(v))return v.some(output);if(typeof v==="object")return Object.values(v as Record<string,unknown>).some(output);return true;}
function buildArgs(ep:Endpoint,input:StudioJobInput){return(ep.parameters??[]).map(p=>{const v=pick(p.parameter_name??p.label??"",input);if(v!=null)return v;const f=fallback(p);if(f!==undefined)return f;if(p.optional||p.parameter_has_default)return undefined;throw new Error(`Required input unavailable: ${p.parameter_name??p.label??"unknown"}`);});}
async function connect(space:string){const id=spaceId(space);let c=clients.get(id);if(c)return c;const sources=typeof window==="undefined"?[id]:[proxyOrigin(id),id];c=(async()=>{let last:unknown;for(const source of sources)for(let a=0;a<3;a++)try{return await Client.connect(source,{status_callback:()=>undefined});}catch(e){last=e;await new Promise(r=>setTimeout(r,700*(a+1)));}throw last instanceof Error?last:new Error(`Could not connect to ${id}`);})();c.catch(()=>clients.delete(id));clients.set(id,c);return c;}
async function getApi(space:string){const id=spaceId(space),cached=apis.get(id);if(cached&&cached.expires>Date.now())return cached.api;const cl=await connect(id),a=await cl.view_api();if(!Object.keys(endpoints(a)).length)throw new Error("Voice service has no usable endpoints");apis.set(id,{api:a,expires:Date.now()+120000});return a;}
function score(name:string,ep:Endpoint,cap:StudioCapability,input:StudioJobInput){const h=norm(`${name} ${ep.fn??""} ${ep.description??""}`),ps=(ep.parameters??[]).map(p=>norm(p.parameter_name??p.label??""));let s=0;if(cap==="voice-clone"){if(!/clone|zeroshot|reference|voiceclone/.test(h))return -1000;if(!ps.some(p=>p.includes("refaudio")||p.includes("referenceaudio")||p.includes("clonerefaudio")||p==="audio"))return -1000;if(!ps.some(p=>p.includes("targettext")||p.includes("clonetargettext")||p.includes("text")||p.includes("prompt")))return -1000;s+=80;if(ps.some(p=>p.includes("reftext")||p.includes("referencetext")))s+=25;if(ps.some(p=>p.includes("xvector")))s+=15;if(ps.some(p=>p.includes("modelsize")||p==="model"))s+=8;}else if(cap==="tts"){if(!/tts|texttospeech|speech|customvoice|voice/.test(h))return -1000;if(!ps.some(p=>p.includes("speaker")||p.includes("voice")))return -1000;if(!ps.some(p=>p.includes("text")||p.includes("prompt")))return -1000;s+=60;if(input.speaker&&ps.some(p=>p.includes("speaker")))s+=25;if(input.speaker&&h.includes(norm(String(input.speaker))))s+=20;if(ps.some(p=>p.includes("modelsize")||p==="model"))s+=8;}else{if(h.includes(cap.replace(/-/g,"")))s+=20;if(h.includes("generate"))s+=8;}for(const p of ep.parameters??[])if(pick(p.parameter_name??p.label??"",input)!==undefined)s+=3;return s;}
async function runCloudflare(provider:FreeRunner,input:StudioJobInput,cap:StudioCapability):Promise<StudioArtifact>{const prompt=typeof input.prompt==="string"?input.prompt.trim():String(input.text??input.lyrics??"").trim();const payload:Record<string,unknown>={capability:cap,prompt,text:prompt,language:input.language,speaker:input.speaker,messages:input.messages};if(cap==="speech-to-text"&&input.audio instanceof Blob){const fd=new FormData();fd.append("audio",input.audio,"speech.webm");const r=await fetch(provider.url,{method:"POST",body:fd});if(!r.ok)throw new Error(`${provider.name}: HTTP ${r.status}`);const value=await r.json();if(!output(value))throw new Error(`${provider.name}: empty result`);return{capability:cap,value,url:artifactUrl(value),provider:provider.name};}const r=await fetch(provider.url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error(`${provider.name}: HTTP ${r.status}`);const ct=r.headers.get("content-type")??"";if(ct.startsWith("audio/")||ct.startsWith("image/")||ct.startsWith("video/")){const blob=await r.blob();if(!blob.size)throw new Error(`${provider.name}: empty result`);return{capability:cap,value:blob,url:URL.createObjectURL(blob),provider:provider.name};}const value=await r.json();if(!output(value))throw new Error(`${provider.name}: empty result`);return{capability:cap,value,url:artifactUrl(value),provider:provider.name};}
async function runQwenOfficial(cl:Client,input:StudioJobInput,cap:StudioCapability):Promise<StudioArtifact>{
  if(cap==="tts"){
    const text=String(input.text??input.target_text??input.prompt??"").trim();
    if(!text)throw new Error("Voice text is empty");
    const language=String(input.language??"English");
    const speaker=canonicalSpeaker(input.speaker);
    const attempts=[[text,language,speaker,"",String(input.model_size??"1.7B")],[text,language,speaker,"",String(input.model_size??"0.6B")]];
    let last="Qwen CustomVoice failed";
    for(const args of attempts){try{const r=await cl.predict("/generate_custom_voice",args);const value=Array.isArray(r)?r:(r?.data??r);const url=artifactUrl(value);if(!url)throw new Error("Qwen returned no playable voice audio");return{capability:cap,value,url:url.startsWith("/")?`${window.location.origin}${url}`:url,provider:"Qwen3-TTS Custom Voice"};}catch(e){last=e instanceof Error?e.message:String(e);}}
    throw new Error(last);
  }
  if(cap==="voice-clone"){
    const sample=input.refAudio??input.referenceAudio??input.audio;
    if(!(sample instanceof Blob))throw new Error("Voice clone sample is missing");
    const text=String(input.target_text??input.text??input.prompt??"").trim();
    if(!text)throw new Error("Voice clone target text is empty");
    const refText=String(input.referenceTranscript??input.refText??"").trim();
    const xOnly=!refText;
    const ref=await handle_file(sample);
    const attempts=[[ref,refText,text,String(input.language??"English"),xOnly,String(input.model_size??"0.6B")],[ref,refText,text,String(input.language??"Auto"),xOnly,"1.7B"]];
    let last="Qwen voice clone failed";
    for(const args of attempts){try{const r=await cl.predict("/generate_voice_clone",args);const value=Array.isArray(r)?r:(r?.data??r);const url=artifactUrl(value);if(!url)throw new Error("Qwen returned no playable cloned audio");return{capability:cap,value,url:url.startsWith("/")?`${window.location.origin}${url}`:url,provider:"Qwen3-TTS Voice Clone"};}catch(e){last=e instanceof Error?e.message:String(e);}}
    throw new Error(last);
  }
  throw new Error("Unsupported Qwen voice operation");
}
async function runOn(provider:FreeRunner,input:StudioJobInput,cap:StudioCapability):Promise<StudioArtifact>{if(provider.url.startsWith("/api/ai/"))return runCloudflare(provider,input,cap);const space=spaceId(provider.url),cl=await connect(space);if(space==="Qwen/Qwen3-TTS"&&(cap==="tts"||cap==="voice-clone"))return runQwenOfficial(cl,input,cap);const map=endpoints(await getApi(space));const candidates=Object.entries(map).map(([name,ep])=>({name,ep,score:score(name,ep,cap,input)})).filter(x=>x.score>-500).sort((a,b)=>b.score-a.score);if(!candidates.length)throw new Error(`${provider.name}: no endpoint accepts the requested operation`);let last="No usable result";for(const c of candidates){try{const args=await Promise.all(buildArgs(c.ep,input).map(async v=>typeof Blob!=="undefined"&&v instanceof Blob?handle_file(v):v));const r=await cl.predict(c.name,args),value=Array.isArray(r)?r:(r?.data??r),url=artifactUrl(value);if(!output(value))throw new Error("Provider returned no usable result");if(["tts","voice-clone"].includes(cap)&&!url)throw new Error("Provider returned no playable voice audio");return{capability:cap,value,url:url?.startsWith("/")?`${proxyOrigin(space)}${url}`:url,provider:provider.name};}catch(e){last=e instanceof Error?e.message:String(e);}}throw new Error(`${provider.name}: ${last}`);}
async function prepareVoice(cap:StudioCapability,input:StudioJobInput){if(cap!=="tts"||typeof window==="undefined")return{cap,input};const next={...input},p=getBuddyVoiceProfile();if(p.language&&p.language!=="Auto")next.language=p.language;if(p.mode==="clone"){const sample=await getBuddyVoiceSample();if(!sample)throw new Error("Your saved voice sample is unavailable. Please record or upload it again.");next.refAudio=sample;next.referenceAudio=sample;next.audio=sample;next.referenceTranscript=p.referenceTranscript||"";next.refText=p.referenceTranscript||"";next.target_text=input.target_text??input.text??input.prompt??"";next.use_xvector_only=!p.referenceTranscript;next.model_size="0.6B";return{cap:"voice-clone" as StudioCapability,input:next};}next.speaker=canonicalSpeaker(p.speaker);next.text=input.text??input.prompt??input.target_text??"";next.model_size="1.7B";return{cap,input:next};}
export async function runStudioJob(capability:StudioCapability,input:StudioJobInput,onStatus?:(s:string)=>void):Promise<StudioArtifact>{const prepared=await prepareVoice(capability,input),providers=runnersFor(prepared.cap),fails:string[]=[];for(const provider of providers)try{onStatus?.("Working…");const result=await Promise.race([runOn(provider,prepared.input,prepared.cap),new Promise<never>((_,rej)=>window.setTimeout(()=>rej(new Error("Timed out")),180000))]);onStatus?.("Ready.");return{...result,capability};}catch(e){fails.push(e instanceof Error?e.message:String(e));}throw new Error(`${capability} could not produce a usable result. ${fails.slice(0,4).join(" | ")}`);}
export function runtimeProviders(cap?:StudioCapability){return cap?runnersFor(cap):FREE_RUNNERS;}
export function artifactText(value:unknown):string{if(typeof value==="string")return value.trim();if(Array.isArray(value))return value.map(artifactText).find(Boolean)??"";if(value&&typeof value==="object")for(const k of["text","response","generated_text","transcription","transcript","content","value","data","output","result"]){const t=artifactText((value as Record<string,unknown>)[k]);if(t)return t;}return"";}
