import { Client, handle_file } from "@gradio/client";
import { FREE_RUNNERS, type FreeRunner, runnersFor } from "./free-runners";
import { getBuddyVoiceProfile, getBuddyVoiceSample } from "./buddy-voice";
export type StudioCapability = "chat" | "speech-to-text" | "music" | "image" | "video" | "voice-clone" | "voice-swap" | "vocal-separation" | "tts";
export type StudioJobInput = Record<string, unknown>;
export type StudioArtifact = { capability: StudioCapability; value: unknown; url: string | null; provider: string };
type Parameter={parameter_name?:string;label?:string;component?:string;type?:string;default?:unknown;optional?:boolean;parameter_has_default?:boolean};
type Endpoint={parameters?:Parameter[];description?:string;fn?:string}; type Api={named_endpoints?:Record<string,Endpoint>;unnamed_endpoints?:Record<string,Endpoint>};
const clients=new Map<string,Promise<Client>>(),apis=new Map<string,{api:Api;expires:number}>();
const norm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]/g,"");
const aliases:Record<string,string[]>={prompt:["prompt","text","message","query","question","lyrics","targettext"],text:["text","prompt","message","lyrics","targettext"],targettext:["targettext","text","prompt","message"],reftext:["reftext","referencetext","transcript","referencetranscript"],referencetext:["referencetext","reftext","transcript","referencetranscript"],audio:["audio","inputaudio","sourceaudio","referenceaudio","refaudio","file"],refaudio:["refaudio","referenceaudio","audio","file"],referenceaudio:["referenceaudio","refaudio","audio","file"],speaker:["speaker","voice","speakerid","voiceid"],modelsize:["modelsize","model","size"],usexvectoronly:["usexvectoronly","xvectoronly","xvector"]};
function pick(name:string,input:StudioJobInput){const n=norm(name);for(const[k,v]of Object.entries(input))if(norm(k)===n&&v!=null)return v;for(const a of aliases[n]??[])for(const[k,v]of Object.entries(input))if(norm(k)===norm(a)&&v!=null)return v;if(n.includes("targettext"))return input.target_text??input.text??input.prompt;if(n.includes("reftext")||n.includes("referencetext")||n.includes("transcript"))return input.referenceTranscript??input.refText??input.transcript;if(n.includes("speaker")||n.includes("voiceid"))return input.speaker;if(n.includes("modelsize")||n==="model")return input.model_size??input.modelSize;if(n.includes("xvector"))return input.use_xvector_only??input.useXvectorOnly;if(n.includes("audio"))return input.refAudio??input.referenceAudio??input.audio;if(n.includes("history")||n.includes("conversation"))return input.history??input.messages??[];return undefined;}
function fallback(p:Parameter){if(p.default!=null)return p.default;if(p.optional||p.parameter_has_default)return undefined;const n=norm(p.parameter_name??p.label??"");if(n.includes("seed"))return -1;if(n.includes("steps"))return 16;if(n.includes("modelsize"))return "0.6B";if(n.includes("xvector"))return true;if(n.includes("language"))return "English";return undefined;}
function endpoints(api:Api){return{...(api.named_endpoints??{}),...(api.unnamed_endpoints??{})};}
function spaceId(space:string){return space.replace(/^https?:\/\/huggingface\.co\/spaces\//,"").replace(/\/$/,"");}
function proxyOrigin(space:string){return `${window.location.origin}/api/hf-space/${encodeURIComponent(spaceId(space))}`;}
function artifactUrl(v:unknown):string|null{if(typeof v==="string")return/^(https?:|blob:|data:|\/)/i.test(v)?v:null;if(typeof Blob!=="undefined"&&v instanceof Blob)return URL.createObjectURL(v);if(Array.isArray(v))for(const x of v){const u=artifactUrl(x);if(u)return u;}if(v&&typeof v==="object")for(const k of["url","uri","src","path","value","data","audio","file"]){const u=artifactUrl((v as Record<string,unknown>)[k]);if(u)return u;}return null;}
function output(v:unknown):boolean{if(v==null)return false;if(typeof v==="string")return v.trim().length>0;if(typeof Blob!=="undefined"&&v instanceof Blob)return v.size>0;if(Array.isArray(v))return v.some(output);if(typeof v==="object")return Object.values(v as Record<string,unknown>).some(output);return true;}
function buildArgs(ep:Endpoint,input:StudioJobInput){return(ep.parameters??[]).map(p=>{const v=pick(p.parameter_name??p.label??"",input);if(v!=null)return v;const f=fallback(p);if(f!==undefined)return f;if(p.optional||p.parameter_has_default)return undefined;throw new Error(`Required input unavailable: ${p.parameter_name??p.label??"unknown"}`);});}
async function connect(space:string){const id=spaceId(space);let c=clients.get(id);if(c)return c;const sources=typeof window==="undefined"?[id]:[proxyOrigin(id),id];c=(async()=>{let last:unknown;for(const source of sources)for(let a=0;a<3;a++)try{return await Client.connect(source,{status_callback:()=>undefined});}catch(e){last=e;await new Promise(r=>setTimeout(r,700*(a+1)));}throw last instanceof Error?last:new Error(`Could not connect to ${id}`);})();c.catch(()=>clients.delete(id));clients.set(id,c);return c;}
async function getApi(space:string){const id=spaceId(space),cached=apis.get(id);if(cached&&cached.expires>Date.now())return cached.api;const cl=await connect(id);const a=await cl.view_api();if(!Object.keys(endpoints(a)).length)throw new Error("Voice service has no usable endpoints");apis.set(id,{api:a,expires:Date.now()+120000});return a;}
function score(name:string,ep:Endpoint,cap:StudioCapability,input:StudioJobInput){const h=norm(`${name} ${ep.fn??""} ${ep.description??""}`),ps=(ep.parameters??[]).map(p=>norm(p.parameter_name??p.label??""));let s=0;if(cap==="voice-clone"){if(!/clone|zeroshot|reference|customvoice/.test(h))return -1000;if(!ps.some(p=>p.includes("refaudio")||p.includes("referenceaudio")||p==="audio"))return -1000;s+=40;if(ps.some(p=>p.includes("targettext")))s+=20;if(ps.some(p=>p.includes("reftext")||p.includes("referencetext")))s+=15;if(ps.some(p=>p.includes("modelsize")))s+=8;}else if(cap==="tts"){if(!/tts|texttospeech|speech|voice/.test(h))return -1000;if(!ps.some(p=>p.includes("speaker")||p.includes("voice")||p.includes("speakerid")))return -1000;s+=30;if(input.speaker&&h.includes(norm(String(input.speaker))))s+=30;}else{if(h.includes(cap.replace(/-/g,"")))s+=20;if(h.includes("generate"))s+=8;}for(const p of ep.parameters??[])if(pick(p.parameter_name??p.label??"",input)!==undefined)s+=3;return s;}
async function runOn(provider:FreeRunner,input:StudioJobInput,cap:StudioCapability):Promise<StudioArtifact>{const space=spaceId(provider.url),cl=await connect(space),map=endpoints(await getApi(space));const candidates=Object.entries(map).map(([name,ep])=>({name,ep,score:score(name,ep,cap,input)})).filter(x=>x.score>-500).sort((a,b)=>b.score-a.score);if(!candidates.length)throw new Error(`${provider.name}: no endpoint accepts the requested voice operation`);let last="No usable result";for(const c of candidates){try{const args=await Promise.all(buildArgs(c.ep,input).map(async v=>typeof Blob!=="undefined"&&v instanceof Blob?handle_file(v):v));const r=await cl.predict(c.name,args),value=Array.isArray(r)?r:(r?.data??r),url=artifactUrl(value);if(!output(value))throw new Error("Provider returned no usable result");if(["tts","voice-clone"].includes(cap)&&!url)throw new Error("Provider returned no playable voice audio");return{capability:cap,value,url:url?.startsWith("/")?`${proxyOrigin(space)}${url}`:url,provider:provider.name};}catch(e){last=e instanceof Error?e.message:String(e);}}throw new Error(`${provider.name}: ${last}`);}
async function prepareVoice(cap:StudioCapability,input:StudioJobInput){if(cap!=="tts"||typeof window==="undefined")return{cap,input};const next={...input},p=getBuddyVoiceProfile();if(p.language&&p.language!=="Auto")next.language=p.language;if(p.mode==="clone"){const sample=await getBuddyVoiceSample();if(!sample)throw new Error("Your saved voice sample is unavailable. Please record or upload it again.");next.refAudio=sample;next.referenceAudio=sample;next.audio=sample;next.referenceTranscript=p.referenceTranscript||"";next.refText=p.referenceTranscript||"";next.target_text=input.target_text??input.text??input.prompt??"";next.use_xvector_only=!p.referenceTranscript;next.model_size="0.6B";return{cap:"voice-clone" as StudioCapability,input:next};}next.speaker=p.speaker;return{cap,input:next};}
export async function runStudioJob(capability:StudioCapability,input:StudioJobInput,onStatus?:(s:string)=>void):Promise<StudioArtifact>{const prepared=await prepareVoice(capability,input),providers=runnersFor(prepared.cap),fails:string[]=[];for(const provider of providers)try{onStatus?.("Working…");const result=await Promise.race([runOn(provider,prepared.input,prepared.cap),new Promise<never>((_,rej)=>window.setTimeout(()=>rej(new Error("Timed out")),180000))]);onStatus?.("Ready.");return{...result,capability};}catch(e){fails.push(e instanceof Error?e.message:String(e));}throw new Error(`${capability} could not produce a usable result. ${fails.slice(0,4).join(" | ")}`);}
export function runtimeProviders(cap?:StudioCapability){return cap?runnersFor(cap):FREE_RUNNERS;}
export function artifactText(value:unknown):string{if(typeof value==="string")return value.trim();if(Array.isArray(value))return value.map(artifactText).find(Boolean)??"";if(value&&typeof value==="object")for(const k of["text","response","generated_text","transcription","transcript","content","value","data","output","result"]){const t=artifactText((value as Record<string,unknown>)[k]);if(t)return t;}return"";}
