type Env = { HF_TOKEN?: string; QWEN_TTS_SPACE_URL?: string };
type Body = { referenceId?: string; audioBase64?: string; audioType?: string; refText?: string; text?: string; language?: string; modelSize?: "0.6B" | "1.7B" };
const SPACE = "https://qwen-qwen3-tts.hf.space";
const cache = new Map<string, { path: string; expires: number }>();
function auth(env: Env): HeadersInit { return env.HF_TOKEN ? { Authorization: `Bearer ${env.HF_TOKEN}` } : {}; }
function ext(type: string) { const t = type.toLowerCase(); return t.includes("webm") ? "webm" : t.includes("mpeg") ? "mp3" : t.includes("ogg") ? "ogg" : "wav"; }
function decode(value: string) { const s = value.replace(/^data:[^,]+,/, "").replace(/\s/g, ""); const b = Uint8Array.from(atob(s), c => c.charCodeAt(0)); return b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength); }
async function upload(space: string, id: string, base64: string, type: string, env: Env, refresh = false) { const key = `${space}|${id}`; const old = cache.get(key); if (!refresh && old && old.expires > Date.now()) return old.path; const f = new FormData(); f.append("files", new Blob([decode(base64)], { type }), `red-reference.${ext(type)}`); const r = await fetch(`${space}/gradio_api/upload`, { method: "POST", headers: auth(env), body: f }); if (!r.ok) throw new Error(`Qwen reference upload failed (${r.status}).`); const j = await r.json() as unknown; if (!Array.isArray(j) || typeof j[0] !== "string") throw new Error("Qwen returned no reference path."); cache.set(key, { path: j[0], expires: Date.now() + 900000 }); return j[0]; }
export type QwenSSEParseResult = { kind: "audio"; payload: unknown[] } | { kind: "error"; message: string } | { kind: "none" };
export function parseQwenSSE(stream: string): QwenSSEParseResult { let event = "", data: string[] = [], result: QwenSSEParseResult = { kind: "none" }; const flush = () => { if (!data.length) return; const raw = data.join("\n").trim(); if (!raw) return; if (event === "error" || event === "cancelled") { try { const p = JSON.parse(raw) as unknown; result = { kind: "error", message: typeof p === "string" ? p : JSON.stringify(p) }; } catch { result = { kind: "error", message: raw }; } return; } if (event !== "complete") return; try { const p = JSON.parse(raw) as unknown; if (Array.isArray(p) && p[0]) result = { kind: "audio", payload: p }; } catch { result = { kind: "error", message: "Qwen returned invalid completed JSON." }; } }; for (const line of stream.split(/\r\n|\n|\r/)) { if (!line.trim()) { flush(); event = ""; data = []; } else if (line.startsWith("event:")) event = line.slice(6).trim(); else if (line.startsWith("data:")) data.push(line.slice(5).trim()); } flush(); return result; }
function fileData(path: string, type: string) { return { path, orig_name: `red-reference.${ext(type)}`, mime_type: type, meta: { _type: "gradio.FileData" } }; }
function toWav(value: unknown): ArrayBuffer | null { if (!Array.isArray(value) || typeof value[0] !== "number" || !Array.isArray(value[1]) || !value[1].length) return null; const sr = Math.round(value[0]); const samples = value[1] as unknown[]; const pcm = new Int16Array(samples.length); for (let i=0;i<samples.length;i++) { const n=Math.max(-1,Math.min(1,Number(samples[i])||0)); pcm[i]=n<0?n*0x8000:n*0x7fff; } const out=new ArrayBuffer(44+pcm.byteLength); const v=new DataView(out); const put=(o:number,s:string)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i));}; put(0,"RIFF");v.setUint32(4,36+pcm.byteLength,true);put(8,"WAVE");put(12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sr,true);v.setUint32(28,sr*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);put(36,"data");v.setUint32(40,pcm.byteLength,true);new Uint8Array(out,44).set(new Uint8Array(pcm.buffer));return out; }
async function generate(space:string,path:string,type:string,body:Body,env:Env):Promise<Response>{ const ref=body.refText?.trim()||""; const size=body.modelSize==="1.7B"?"1.7B":"0.6B"; const start=await fetch(`${space}/gradio_api/call/generate_voice_clone`,{method:"POST",headers:{...auth(env),"content-type":"application/json"},body:JSON.stringify({data:[fileData(path,type),ref,body.text!.trim().replace(/\s+/g," ").slice(0,220),body.language||"English",!ref,size]})}); if(!start.ok)throw new Error(`Qwen voice clone start failed (${start.status}).`); const job=await start.json() as {event_id?:string}; if(!job.event_id)throw new Error("Qwen returned no voice-clone job ID."); const r=await fetch(`${space}/gradio_api/call/generate_voice_clone/${encodeURIComponent(job.event_id)}`,{headers:{...auth(env),Accept:"text/event-stream"}}); if(!r.ok)throw new Error(`Qwen voice clone job failed (${r.status}).`); const p=parseQwenSSE(await r.text()); if(p.kind==="error")throw new Error(`Qwen voice clone: ${p.message.slice(0,500)}`); if(p.kind!=="audio")throw new Error("Qwen completed without cloned audio."); const w=toWav(p.payload[0]); if(w)return new Response(w,{headers:{"content-type":"audio/wav","cache-control":"no-store","x-clone-provider":`Qwen3-TTS Base ${size} reference clone`,`x-red-voice-route":"qwen3-reference-clone"}}); const first=p.payload[0]; const item=first&&typeof first==="object"?first as Record<string,unknown>:null; const url=typeof first==="string"?first:item&&typeof item.url==="string"?item.url:item&&typeof item.path==="string"?`${space}/gradio_api/file=${item.path.replace(/^\//,"")}`:""; if(!url)throw new Error("Qwen returned no playable cloned audio artifact."); const a=await fetch(url.startsWith("http")?url:`${space}${url}`,{headers:auth(env)}); if(!a.ok||!a.body)throw new Error(`Qwen audio download failed (${a.status}).`); const h=new Headers(a.headers);h.set("cache-control","no-store");h.set("x-clone-provider",`Qwen3-TTS Base ${size} reference clone`);h.set("x-red-voice-route","qwen3-reference-clone");return new Response(a.body,{status:200,headers:h}); }
export async function handleVoiceClone(request:Request,env:Env):Promise<Response>{ if(request.method!=="POST")return Response.json({ok:false,error:"POST required."},{status:405}); let body:Body; try{body=await request.json() as Body;}catch{return Response.json({ok:false,error:"The clone request was not valid JSON."},{status:400});} if(!body.referenceId?.trim()||!body.audioBase64)return Response.json({ok:false,error:"A Red voice reference is required."},{status:400});if(!body.text?.trim())return Response.json({ok:false,error:"Target text is required."},{status:400});const type=String(body.audioType||"audio/wav"),id=body.referenceId.trim();try{let path=await upload(SPACE,id,body.audioBase64,type,env);try{return await generate(SPACE,path,type,body,env);}catch{path=await upload(SPACE,id,body.audioBase64,type,env,true);return await generate(SPACE,path,type,body,env);}}catch(e){return Response.json({ok:false,error:`Red voice cloning failed on Qwen3-TTS: ${e instanceof Error?e.message:String(e)}`},{status:502,headers:{"cache-control":"no-store","x-red-voice-route":"qwen3-reference-clone"}});}}
